### ISSUE TITLE
Semver and peerdependencies

### ISSUE THREAD

**Issue by Dignifiedquire** [karma-runner/integration-tests#5]
After I started using proper semver versions for the canary releases currently integration tests are broken for the canary branch :( 
The issue is that `>= 0.12.0` does not include a version like `0.13.0-rc.0` as it only uses stable versions. Any ideas or thoughts on how to best fix this?

cc @karma-runner/contributors 

**Update**

Removing all peerDependencies as describe below:

- [ ] karma-jasmine 2 (PR exists)
- [ ] karma-jasmine
- [ ] karma-mocha (PR exists)
- [ ] karma-qunit
- [ ] karma-junit-reporter
- [x] karma-coverage
- [ ] karma-requirejs
- [ ] karma-dojo
- [ ] karma-live-preprocessor
- [ ] karma-html2js-preprocessor
- [ ] karma-ng-html2js-preprocessor
- [ ] karma-coffee-preprocessor
- [ ] karma-googmodule-preprocessor
- [ ] karma-phantomjs-launcher (PR exists)
- [ ] karma-chrome-launcher
- [ ] karma-ie-launcher
- [ ] karma-safari-launcher
- [ ] karma-firefox-launcher
- [ ] karma-sauce-launcher
- [ ] karma-browserstack-launcher
- [ ] karma-webdriver-launcher
- [ ] karma-opera-launcher
- [ ] karma-slimer-launcher
- [ ] karma-opera-launcher
- [ ] karma-script-launcher

## External

- [ ] karma-webpack (PR exists)
- [x] karma-babel

**Comment by Dignifiedquire** [comment]
Adding this to all plugins should resolve the issue for the new versions: 

```json
"karma": ">=0.9.0 || >=0.13.0-rc.0"
```

**Comment by maksimr** [comment]
@Dignifiedquire what about remove `peerDependencies` from plugins? :)

**Comment by Dignifiedquire** [comment]
@maksimr I'm getting the feeling that removing it is the best way forward

**Comment by Dignifiedquire** [comment]
After some more contemplation and references like https://github.com/npm/npm/issues/5080 I think the way forward should be:

* Make karma (plugins) more intelligent and let them check the karma object they work with if there is a need to depend on specific features. 
* Remove `karma` from `peerDependencies` and `dependencies`, except for `grunt-karma` which should have a direct dependency on `karma` as it requires it directly. There I will switch to using the proposed  `>= 0.12.0 || >= 0.13.0-rc.0` which will have to be updated for new releases.

If I don't hear any arguments against this, I will make the needed prs/changes starting tomorrow

// cc @karma-runner/contributors
